/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SubjectsSubjectIdRouteImport } from './routes/subjects.$subjectId'
import { Route as SubjectsSubjectIdIndexRouteImport } from './routes/subjects.$subjectId.index'
import { Route as SubjectsSubjectIdNotesRouteImport } from './routes/subjects.$subjectId.notes'
import { Route as SubjectsSubjectIdExamsRouteImport } from './routes/subjects.$subjectId.exams'
import { Route as SubjectsSubjectIdExamsIndexRouteImport } from './routes/subjects.$subjectId.exams.index'
import { Route as SubjectsSubjectIdNotesNoteIdRouteImport } from './routes/subjects.$subjectId.notes.$noteId'
import { Route as SubjectsSubjectIdExamsExamIdRouteImport } from './routes/subjects.$subjectId.exams.$examId'
import { Route as SubjectsSubjectIdExamsExamIdIndexRouteImport } from './routes/subjects.$subjectId.exams.$examId.index'
import { Route as SubjectsSubjectIdExamsExamIdAttemptRouteImport } from './routes/subjects.$subjectId.exams.$examId.attempt'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdRoute = SubjectsSubjectIdRouteImport.update({
  id: '/subjects/$subjectId',
  path: '/subjects/$subjectId',
  getParentRoute: () => rootRouteImport,
} as any)
const SubjectsSubjectIdIndexRoute = SubjectsSubjectIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SubjectsSubjectIdRoute,
} as any)
const SubjectsSubjectIdNotesRoute = SubjectsSubjectIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => SubjectsSubjectIdRoute,
} as any)
const SubjectsSubjectIdExamsRoute = SubjectsSubjectIdExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => SubjectsSubjectIdRoute,
} as any)
const SubjectsSubjectIdExamsIndexRoute =
  SubjectsSubjectIdExamsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SubjectsSubjectIdExamsRoute,
  } as any)
const SubjectsSubjectIdNotesNoteIdRoute =
  SubjectsSubjectIdNotesNoteIdRouteImport.update({
    id: '/$noteId',
    path: '/$noteId',
    getParentRoute: () => SubjectsSubjectIdNotesRoute,
  } as any)
const SubjectsSubjectIdExamsExamIdRoute =
  SubjectsSubjectIdExamsExamIdRouteImport.update({
    id: '/$examId',
    path: '/$examId',
    getParentRoute: () => SubjectsSubjectIdExamsRoute,
  } as any)
const SubjectsSubjectIdExamsExamIdIndexRoute =
  SubjectsSubjectIdExamsExamIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => SubjectsSubjectIdExamsExamIdRoute,
  } as any)
const SubjectsSubjectIdExamsExamIdAttemptRoute =
  SubjectsSubjectIdExamsExamIdAttemptRouteImport.update({
    id: '/attempt',
    path: '/attempt',
    getParentRoute: () => SubjectsSubjectIdExamsExamIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRouteWithChildren
  '/subjects/$subjectId/exams': typeof SubjectsSubjectIdExamsRouteWithChildren
  '/subjects/$subjectId/notes': typeof SubjectsSubjectIdNotesRouteWithChildren
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/exams/$examId': typeof SubjectsSubjectIdExamsExamIdRouteWithChildren
  '/subjects/$subjectId/notes/$noteId': typeof SubjectsSubjectIdNotesNoteIdRoute
  '/subjects/$subjectId/exams/': typeof SubjectsSubjectIdExamsIndexRoute
  '/subjects/$subjectId/exams/$examId/attempt': typeof SubjectsSubjectIdExamsExamIdAttemptRoute
  '/subjects/$subjectId/exams/$examId/': typeof SubjectsSubjectIdExamsExamIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/subjects/$subjectId/notes': typeof SubjectsSubjectIdNotesRouteWithChildren
  '/subjects/$subjectId': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/notes/$noteId': typeof SubjectsSubjectIdNotesNoteIdRoute
  '/subjects/$subjectId/exams': typeof SubjectsSubjectIdExamsIndexRoute
  '/subjects/$subjectId/exams/$examId/attempt': typeof SubjectsSubjectIdExamsExamIdAttemptRoute
  '/subjects/$subjectId/exams/$examId': typeof SubjectsSubjectIdExamsExamIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/subjects/$subjectId': typeof SubjectsSubjectIdRouteWithChildren
  '/subjects/$subjectId/exams': typeof SubjectsSubjectIdExamsRouteWithChildren
  '/subjects/$subjectId/notes': typeof SubjectsSubjectIdNotesRouteWithChildren
  '/subjects/$subjectId/': typeof SubjectsSubjectIdIndexRoute
  '/subjects/$subjectId/exams/$examId': typeof SubjectsSubjectIdExamsExamIdRouteWithChildren
  '/subjects/$subjectId/notes/$noteId': typeof SubjectsSubjectIdNotesNoteIdRoute
  '/subjects/$subjectId/exams/': typeof SubjectsSubjectIdExamsIndexRoute
  '/subjects/$subjectId/exams/$examId/attempt': typeof SubjectsSubjectIdExamsExamIdAttemptRoute
  '/subjects/$subjectId/exams/$examId/': typeof SubjectsSubjectIdExamsExamIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/exams'
    | '/subjects/$subjectId/notes'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/exams/$examId'
    | '/subjects/$subjectId/notes/$noteId'
    | '/subjects/$subjectId/exams/'
    | '/subjects/$subjectId/exams/$examId/attempt'
    | '/subjects/$subjectId/exams/$examId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/subjects/$subjectId/notes'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/notes/$noteId'
    | '/subjects/$subjectId/exams'
    | '/subjects/$subjectId/exams/$examId/attempt'
    | '/subjects/$subjectId/exams/$examId'
  id:
    | '__root__'
    | '/'
    | '/subjects/$subjectId'
    | '/subjects/$subjectId/exams'
    | '/subjects/$subjectId/notes'
    | '/subjects/$subjectId/'
    | '/subjects/$subjectId/exams/$examId'
    | '/subjects/$subjectId/notes/$noteId'
    | '/subjects/$subjectId/exams/'
    | '/subjects/$subjectId/exams/$examId/attempt'
    | '/subjects/$subjectId/exams/$examId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SubjectsSubjectIdRoute: typeof SubjectsSubjectIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId': {
      id: '/subjects/$subjectId'
      path: '/subjects/$subjectId'
      fullPath: '/subjects/$subjectId'
      preLoaderRoute: typeof SubjectsSubjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subjects/$subjectId/': {
      id: '/subjects/$subjectId/'
      path: '/'
      fullPath: '/subjects/$subjectId/'
      preLoaderRoute: typeof SubjectsSubjectIdIndexRouteImport
      parentRoute: typeof SubjectsSubjectIdRoute
    }
    '/subjects/$subjectId/notes': {
      id: '/subjects/$subjectId/notes'
      path: '/notes'
      fullPath: '/subjects/$subjectId/notes'
      preLoaderRoute: typeof SubjectsSubjectIdNotesRouteImport
      parentRoute: typeof SubjectsSubjectIdRoute
    }
    '/subjects/$subjectId/exams': {
      id: '/subjects/$subjectId/exams'
      path: '/exams'
      fullPath: '/subjects/$subjectId/exams'
      preLoaderRoute: typeof SubjectsSubjectIdExamsRouteImport
      parentRoute: typeof SubjectsSubjectIdRoute
    }
    '/subjects/$subjectId/exams/': {
      id: '/subjects/$subjectId/exams/'
      path: '/'
      fullPath: '/subjects/$subjectId/exams/'
      preLoaderRoute: typeof SubjectsSubjectIdExamsIndexRouteImport
      parentRoute: typeof SubjectsSubjectIdExamsRoute
    }
    '/subjects/$subjectId/notes/$noteId': {
      id: '/subjects/$subjectId/notes/$noteId'
      path: '/$noteId'
      fullPath: '/subjects/$subjectId/notes/$noteId'
      preLoaderRoute: typeof SubjectsSubjectIdNotesNoteIdRouteImport
      parentRoute: typeof SubjectsSubjectIdNotesRoute
    }
    '/subjects/$subjectId/exams/$examId': {
      id: '/subjects/$subjectId/exams/$examId'
      path: '/$examId'
      fullPath: '/subjects/$subjectId/exams/$examId'
      preLoaderRoute: typeof SubjectsSubjectIdExamsExamIdRouteImport
      parentRoute: typeof SubjectsSubjectIdExamsRoute
    }
    '/subjects/$subjectId/exams/$examId/': {
      id: '/subjects/$subjectId/exams/$examId/'
      path: '/'
      fullPath: '/subjects/$subjectId/exams/$examId/'
      preLoaderRoute: typeof SubjectsSubjectIdExamsExamIdIndexRouteImport
      parentRoute: typeof SubjectsSubjectIdExamsExamIdRoute
    }
    '/subjects/$subjectId/exams/$examId/attempt': {
      id: '/subjects/$subjectId/exams/$examId/attempt'
      path: '/attempt'
      fullPath: '/subjects/$subjectId/exams/$examId/attempt'
      preLoaderRoute: typeof SubjectsSubjectIdExamsExamIdAttemptRouteImport
      parentRoute: typeof SubjectsSubjectIdExamsExamIdRoute
    }
  }
}

interface SubjectsSubjectIdExamsExamIdRouteChildren {
  SubjectsSubjectIdExamsExamIdAttemptRoute: typeof SubjectsSubjectIdExamsExamIdAttemptRoute
  SubjectsSubjectIdExamsExamIdIndexRoute: typeof SubjectsSubjectIdExamsExamIdIndexRoute
}

const SubjectsSubjectIdExamsExamIdRouteChildren: SubjectsSubjectIdExamsExamIdRouteChildren =
  {
    SubjectsSubjectIdExamsExamIdAttemptRoute:
      SubjectsSubjectIdExamsExamIdAttemptRoute,
    SubjectsSubjectIdExamsExamIdIndexRoute:
      SubjectsSubjectIdExamsExamIdIndexRoute,
  }

const SubjectsSubjectIdExamsExamIdRouteWithChildren =
  SubjectsSubjectIdExamsExamIdRoute._addFileChildren(
    SubjectsSubjectIdExamsExamIdRouteChildren,
  )

interface SubjectsSubjectIdExamsRouteChildren {
  SubjectsSubjectIdExamsExamIdRoute: typeof SubjectsSubjectIdExamsExamIdRouteWithChildren
  SubjectsSubjectIdExamsIndexRoute: typeof SubjectsSubjectIdExamsIndexRoute
}

const SubjectsSubjectIdExamsRouteChildren: SubjectsSubjectIdExamsRouteChildren =
  {
    SubjectsSubjectIdExamsExamIdRoute:
      SubjectsSubjectIdExamsExamIdRouteWithChildren,
    SubjectsSubjectIdExamsIndexRoute: SubjectsSubjectIdExamsIndexRoute,
  }

const SubjectsSubjectIdExamsRouteWithChildren =
  SubjectsSubjectIdExamsRoute._addFileChildren(
    SubjectsSubjectIdExamsRouteChildren,
  )

interface SubjectsSubjectIdNotesRouteChildren {
  SubjectsSubjectIdNotesNoteIdRoute: typeof SubjectsSubjectIdNotesNoteIdRoute
}

const SubjectsSubjectIdNotesRouteChildren: SubjectsSubjectIdNotesRouteChildren =
  {
    SubjectsSubjectIdNotesNoteIdRoute: SubjectsSubjectIdNotesNoteIdRoute,
  }

const SubjectsSubjectIdNotesRouteWithChildren =
  SubjectsSubjectIdNotesRoute._addFileChildren(
    SubjectsSubjectIdNotesRouteChildren,
  )

interface SubjectsSubjectIdRouteChildren {
  SubjectsSubjectIdExamsRoute: typeof SubjectsSubjectIdExamsRouteWithChildren
  SubjectsSubjectIdNotesRoute: typeof SubjectsSubjectIdNotesRouteWithChildren
  SubjectsSubjectIdIndexRoute: typeof SubjectsSubjectIdIndexRoute
}

const SubjectsSubjectIdRouteChildren: SubjectsSubjectIdRouteChildren = {
  SubjectsSubjectIdExamsRoute: SubjectsSubjectIdExamsRouteWithChildren,
  SubjectsSubjectIdNotesRoute: SubjectsSubjectIdNotesRouteWithChildren,
  SubjectsSubjectIdIndexRoute: SubjectsSubjectIdIndexRoute,
}

const SubjectsSubjectIdRouteWithChildren =
  SubjectsSubjectIdRoute._addFileChildren(SubjectsSubjectIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SubjectsSubjectIdRoute: SubjectsSubjectIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
